# Generated by Django 5.2 on 2025-05-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_remove_project_tags_project_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="members_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
