# Generated by Django 5.2 on 2025-05-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="category",
            field=models.CharField(
                choices=[
                    ("discipline", "Discipline"),
                    ("technology", "Technology"),
                    ("method", "Method"),
                ],
                max_length=100,
            ),
        ),
    ]
