# Generated by Django 5.2 on 2025-05-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
