# Generated by Django 5.2 on 2025-05-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
